apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: three-tier-app
  labels:
    app: postgres
    app.kubernetes.io/name: three-tier-kubernetes-app
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: postgres
