apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: three-tier-app
  labels:
    app: frontend
    app.kubernetes.io/name: three-tier-kubernetes-app
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: frontend
