apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: three-tier-app
  labels:
    app.kubernetes.io/name: three-tier-kubernetes-app
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "postgres"
  VITE_API_URL: "/api"
