apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-policy
  namespace: three-tier-app
  labels:
    app.kubernetes.io/name: three-tier-kubernetes-app
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
    - Ingress
  ingress:
    # Allow incoming traffic to Postgres (5432) ONLY from the Backend pods
    - from:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-policy
  namespace: three-tier-app
  labels:
    app.kubernetes.io/name: three-tier-kubernetes-app
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
    - Ingress
  ingress:
    # Allow incoming traffic to FastAPI (8000) from the Frontend pods
    - from:
        - podSelector:
            matchLabels:
              app: frontend
      ports:
        - protocol: TCP
          port: 8000
    # Also allow incoming traffic from Ingress controller namespace (e.g. ingress-nginx)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-policy
  namespace: three-tier-app
  labels:
    app.kubernetes.io/name: three-tier-kubernetes-app
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Ingress
  ingress:
    # Allow incoming HTTP traffic to Frontend (80) from anywhere (Ingress controller routing)
    - ports:
        - protocol: TCP
          port: 80
