apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: three-tier-app
  labels:
    app.kubernetes.io/name: three-tier-kubernetes-app
spec:
  hard:
    pods: "20"
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: namespace-limits
  namespace: three-tier-app
  labels:
    app.kubernetes.io/name: three-tier-kubernetes-app
spec:
  limits:
    - default:
        cpu: 300m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
